### Products
GET http://localhost:3000/products

### POST Products
POST  http://localhost:3000/products
Content-Type: application/json

{
  "name": "mouse",
  "price": 150
}

### Product by ID
GET http://localhost:3000/products/2

### Delete product by ID
DELETE http://localhost:3000/products/2

### Actualizar 
PUT http://localhost:3000/products/2
Content-Type: application/json

{
  "name": "mouse gaming",
  "price": 200
}